### ISSUE TITLE
How can I expand the title of the page?

### ISSUE THREAD

**Issue by andreicek** [caarlos0-graveyard/up#10]
My super long name won't fit in the navbar-brand. Thanks!

**Comment by caarlos0** [comment]
You can fix it [here](https://github.com/caarlos0/up/blob/gh-pages/_layouts/layout.html#L38)... I recommend you, as it is your blog, put it strongly typed in here, or to made a pull a request with a fix like `{{ site.short_title || site.title }}`.

Thanks

**Comment by andreicek** [comment]
I am afraid that you did not understand my problem. I attached a screenshot.
![screen shot 2013-06-03 at 3 6 13 25](https://f.cloud.github.com/assets/1520965/599010/6134353a-cc40-11e2-99e8-776be598dba6.png)

Thank you!

**Comment by caarlos0** [comment]
Hmm, looks like a bootstrap issue... (maybe because is an unstable version)

Maybe we can report it to bootstrap team =D

**Comment by andreicek** [comment]
I fixed it! Take a look at it here. https://github.com/andreicek/andreicek.github.io/blob/932f6b9b6a8dfd273739a47f1b3e19971d1927cf/css/up.css

Thanks!
