### ISSUE TITLE
Missing Favicon

### ISSUE THREAD

**Issue by arvind-naidu** [caarlos0-graveyard/up#14]
# Missing Favicon

For starters, love the theme from the bottom of my heart. Only one thing, the favicon is not appearing locally using jekyll serve or on Github pages.
1. I did run into some problems with rackmagic but go that sorted out.
2. Had all the favicons placed at the root of the file just like it was.
3. Tried to load with jekyll serve and nothing comes up
4. Pushed it to Github and still nothing.

You can visit [my page](http://arvind-naidu.github.io) here and see the problem.
### Update

_It works on Firefox but not on Chrome_

**Comment by caarlos0** [comment]
Weird.. it works here...

![screen shot 2013-08-28 at 3 50 31 pm](https://f.cloud.github.com/assets/245435/1044503/c1f071de-1012-11e3-9cdb-03d741ee97d3.png)

**Comment by caarlos0** [comment]
Have you tried to open in an incognito window? Maybe it's just a cache issue.
Cheers

**Comment by arvind-naidu** [comment]
Well, maybe it just doesn't work on Linux. It's okay then. Thanks a lot for helping me out man.

**Comment by caarlos0** [comment]
Actually it works on my Linux desktop too (at work)..

Cheers.

**Comment by arvind-naidu** [comment]
Haha! Then, I'll give my Linux machine a restart and see how it goes. _Clearing cache didn't work_
