### ISSUE TITLE
Error message at the foot of the UP home page on Github

### ISSUE THREAD

**Issue by StevenBlack** [caarlos0-graveyard/up#5]
At the very bottom of

http://caarlos0.github.com/posts/up-a-jekyll-theme/

observe:

```
Included file 'gauges.html' not found in _includes directory
```

**Comment by caarlos0** [comment]
Fixed. It's a feature that I didn't add in original Up theme yet.

Thanks for reporting this.

**Comment by caarlos0** [comment]
well, now Up has it.
