### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by jcldavid** [caarlos0-graveyard/up#7]
Do I have to touch it? I added a new css for the pygments highlighting:

``` bash
$ make build
##################################################
Building Up...
##################################################
cat: css/{bootstrap,custom,monokai,bootstrap-responsive,font-awesome}.css: No such file or directory
make: *** [build] Error 1
```

I added `monokai.css`

**Comment by caarlos0** [comment]
Not really. Just check the import path...

BTW, are you adding the imports to `up.less`?

**Comment by jcldavid** [comment]
Nope, there's no file `up.less`. I just modified the makefile and added the file `monokai.css` in the `css` dir. But thanks anyway, I think it's just with the version of bash I have? I changed the `cat` line to:

```
cat css/bootstrap.css css/custom.css css/bootstrap-responsive.css css/font-awesome.css > css/up.css
```

**Comment by caarlos0** [comment]
Oh sorry, I get confused with the next version..

Yeah, probably is the bash. I tested it under zsh...
